export const permissionsMatrix = {
  super_admin: {
    viewDashboard: true,
    viewUsers: true,
    suspendUsers: true,
    viewJourneys: true,
    forceAbandonJourney: true,
    reviewFlaggedCheckins: true,
    processDisputes: true,
    viewStakes: true,
    manageCategories: true,
    sendAnnouncements: true,
    manageAdminAccounts: true,
    editPlatformConfig: true,
  },
  moderator: {
    viewDashboard: true,
    viewUsers: true,
    suspendUsers: true,
    viewJourneys: true,
    forceAbandonJourney: true,
    reviewFlaggedCheckins: true,
    processDisputes: true,
    viewStakes: false,
    manageCategories: true,
    sendAnnouncements: true,
    manageAdminAccounts: false,
    editPlatformConfig: false,
  },
  support: {
    viewDashboard: true,
    viewUsers: true,
    suspendUsers: false,
    viewJourneys: true,
    forceAbandonJourney: false,
    reviewFlaggedCheckins: true,
    processDisputes: true,
    viewStakes: false,
    manageCategories: false,
    sendAnnouncements: false,
    manageAdminAccounts: false,
    editPlatformConfig: false,
  },
}
